name: Package the project for distribution

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Compile to zip
      run: python package.py automatrix.zip
    - name: Attach automatrix.zip to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./automatrix.zip
        asset_name: automatrix.zip
        asset_content_type: "application/zip"
    - name: Attach automatrix.sty to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./automatrix.sty
        asset_name: automatrix.sty
        asset_content_type: "application/x-tex"
    
